#Site
site_name: DSA-Online LeetCode Solutions
site_description: Collection of LeetCode problems with solutions
site_author: ASC
site_url:

# Repository
repo_name: DSA-Online
repo_url: https://github.com/akhilub/DSA-Online

# Theme configuration
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - navigation.footer

# Extensions
markdown_extensions:
  - mdx_math
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true

  - def_list
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html

# Extra JavaScript for math rendering
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# extra:
#   social:
#     - icon:
#       link:
#     - icon:
#       link:

copyright: Copyright &copy; 2025 ASC

# Plugins
plugins:
  - search
  - mermaid2

# Navigation structure
nav:
  - Home: index.md
  - Problems:
      - 1. Two Sum: solutions/1.md
      - 2. Add Two Number: solutions/2.md
