name: Deploy DSA-Bible

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "mkdocs-material[offline]"

      - name: Create mkdocs.yml
        shell: bash
        run: |
          cat > mkdocs.yml << 'EOL'
          ${{ secrets.MKDOCS_CONFIG }}
          EOL

      - name: Generate navigation structure
        run: |
          python3 scripts/gen_nav.py

      - name: Create CNAME file
        run: |
          echo "dsa.akhilsin.com" > docs/CNAME

      - name: Deploy
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          mkdocs gh-deploy --force

      - name: Reset the commit history
        run: |
          git checkout --orphan orphan
          git add --all
          git config user.name "akhilub"
          git config user.email $EMAIL
          git commit -m 'Leetcode solutions for DSA-Bible'
          git branch -D main
          git branch -m main
          git push origin main -f
        env:
          EMAIL: ${{ secrets.EMAIL }}
