name: Deploy DSA-Online

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          pip install mkdocs
          pip install python-markdown-math
          pip install mkdocs-mermaid2-plugin

      - name: Create mkdocs.yml
        run: |
          echo "${{ secrets.MKDOCS_CONFIG }}" > mkdocs.yml

      - name: Deploy
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          mkdocs gh-deploy --force
